- hosts: localhost
  become: true

  collections:
    - murznn.ddev
    - orjangj.editors
    
  roles:
    - ddev
    - orjangj.editors.vscode

  tasks:

    - name: install crow-translate
      import_tasks: tasks/add-ppas.yml
      vars:
        ppas: 
          - "ppa:jonmagon/crow-translate" 
          - "ppa:dschopf/plasma-applet-qalculate" 

    - name: install apt packages
      apt:
        pkg:
          - age
          - code
          - ksnip
          - crow-translate
          - plasma-applet-qalculate

    - name: install snap packages
      community.general.snap:
        name:
          - skype
          - zoom-client
          - kubectl
          - kontena-lens
          - chezmoi
          - spotify

    - name: install snap classic packages
      community.general.snap:
        name:
          - chezmoi
        classic: true

