- hosts: localhost
  become: true

  collections:
    - murznn.ddev
    - orjangj.editors

  roles:
    - ddev
    - orjangj.editors.vscode

  tasks:
    - name: Install PPAs
      import_tasks: tasks/add-ppas.yml
      vars:
        ppas:
          - 'ppa:jonmagon/crow-translate'
          - 'ppa:dschopf/plasma-applet-qalculate'

    - name: Install apt packages
      apt:
        pkg:
          - age
          - code
          - ksnip
          - crow-translate
          - plasma-applet-qalculate

    - name: Install snap packages
      community.general.snap:
        name:
          - zoom-client
          - chezmoi
          - spotify

    - name: Install snap classic packages
      community.general.snap:
        name:
          - chezmoi
          - kontena-lens
          - kubectl
          - skype
        classic: true
